THEMES = {
    1: {"numbers_nine": "Числа от 1 до 9",
        "numbers_ten": "Числа от 0 до 10", 
        "numbers_twenty": "Числа от 11 до 20",
        "length": "Длина. Понятие длины",
        "text_tasks": "Решение текстовых задач"},
    2: {"multiplication":"Умножение",
        "division":"Деление",
        "procedure":"Порядок действий",
        "measure_of_length":"Мера длины",
        "measure_of_mass":"Мера массы",
        "measure_of_time":"Мера времени"},
    3: {"numbers":"Числа",
        "sizes":"Величины",
        "addition_subtraction":"Сложение и вычитание",
        "multiplication_division":"Умножение и деление",
        "numeric_expression":"Числовое выражение",
        "problem_solving":"Решение задач"},
    4: {"decimal_fractions":"Десятичные дроби",
        "movement_tasks":"Задачи на движение",
        "performance_tasks":"Задачи на производительность",
        "closing_speed":"Скорость сближения",
        "speed_of_distancing":"Скорость удаления",
        "linear_equations":"Линейные уравнения"},
    5: {"natural_numbers":"Натуральные числа",
        "initial_geometry":"Начальные геометрические понятия",
        "number_decomposition":"Разложение чисел на простые множители",
        "criterion_divisibility":"Признаки делимости",
        "simple_compound":"Простые и составные числа",
        "common_fractions":"Обыкновенные дроби",
        "mixed_numbers":"Смешанные дроби"},
    6: {"natural_numbers":"Натуральные числа",
        "percent":"Проценты",
        "rational_numbers":"Рациональные числа",
        "basics_of_geometry":"Основы геометрии",
        "transformation_of_literal_expressions":"Преобразование буквенных выражений"},
    7: {"algebraic_expressions":"Алгебраические выражения",
        "linear_function":"Линейная функция",
        "simple_equations":"Системы двух линейных уравнений с двумя неизвестными",
        "natural_degree":"Степень с натуральным показателем",
        "monomial":"Одночлен. Арифметические действия с одночленами",
        "polynomial":"Многочлен. Арифметические действия с многочленами"},
    8: {"quadratic_equations":"Квадратные уравнения",
        "linear_inequalities":"Линейные неравенства",
        "module":"Модуль",
        "square_root":"Квадратный корень",
        "quadratic_function":"Квадратичная функция",
        "area_of_​​a_rectangle":"Площадь прямоугольника"},
    9: {"systems_solution":"Решение систем уравнений",
        "interval_method":"Метод интервалов",
        "function_concept":"Понятие функции и способы её задания",
        "function_properties":"Свойства функций",
        "cube_root":"Функция кубического корня",
        "arithmetic_progression":"Арифметическая прогрессия",
        "geometrical_progression":"Геометрическая прогрессия"}
}

