THEMES = {
    1: {"addition": "Сложение",
        "subtraction": "Вычитание", 
        "number_comparison": "Сравнение чисел",
        "greater_than": "Больше",
        "less_than": "Меньше",
        "shapes": "Фигуры"},
    2: {"multiplication":"Умножение",
        "division":"Деление",
        "procedure":"Порядок действий"},
    3: ["Дроби"],
    4: {"decimal_fractions":"Десятичные дроби"},
    5: ["Обыкновенные дроби"],
    6: {"natural_numbers":"Натуральные числа",
        "percent":"Проценты",
        "rational_numbers":"Рациональные числа",
        "basics_of_geometry":"Основы геометрии",
        "transformation_of_literal_expressions":"Преобразование буквенных выражений"},
    7: {"algebraic_expressions":"Алгебраические выражения",
        "linear_function":"Линейная функция",
        "simple_equations":"Системы двух линейных уравнений с двумя неизвестными"},
    8: {"quadratic_equations":"Квадратные уравнения",
        "linear_inequalities":"Линейные неравенства",
        "module":"Модуль",
        "square_root":"Квадратный корень"},
    9: {"systems_solution":"Решение систем уравнений",
        "interval_method":"Метод интервалов",
        "function_concept":"Понятие функции и способы её задания",
        "function_properties":"Свойства функций",
        "cube_root":"Функция кубического корня",
        "arithmetic_progression":"Арифметическая прогрессия",
        "geometrical_progression":"Геометрическая прогрессия"}
}
